name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: "adithya-naik>"
          projectKey: "adithya-naik_SiteForge"
          projectName: "SiteForage"
          token: ${{ secrets.SONAR_TOKEN }}
